### ISSUE TITLE
most useful thanks, + adapt for IP-based server

### ISSUE THREAD

**Issue by berteh** [unconv/php-localhost-ssl#1]
very clear explanations, thanks. Turned out most useful to be able to access html5 geolocalisation feature for quick dev that is only enabled through https in recent smartphones.

Using a custom domain name is complicated on smartphones since editing the /etc/hosts in non-rooted environment is impossible. To make the local PHP dev server accessible via HTTPS for any device in my local network (with IP), I adapted the following 2 lines:

    # start PHP built in server
    php -S localhost:$2 &
    
    # start stunnel
    sudo stunnel3 -f -d $1:$3 -r localhost:$2 -p $CERT_FOLDER/$1-bundle.pem

and then call your existing (192.168.1.10 being the local IP of my dev server):

    serveit 192.168.1.10 8080 443

**Comment by unconv** [comment]
Thanks for the contribution! I merged the pull request you created with some modifications. Basically opening the PHP server to 0.0.0.0 is not necessary as far as I can tell, if you use a local IP instead of a domain when running the script. It was necessary, however, to add the given domain/IP to both the `php -S` command and the `stunnel` command to be able to access the local server with a local IP address.

**Comment by berteh** [comment]
thanks. 
Opening 0.0.0.0 had (to me) the (only) advantage to have the script accessible at the same time via http (eg to download the rootCA) and https (to test the script).
running php -S with the $1 ip/domain prevented simultaneous IP based HTTP(no S) access from another machine, afaik.
